# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_cadastro = QtWidgets.QFrame(self.centralwidget)
        self.frame_cadastro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cadastro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cadastro.setObjectName("frame_cadastro")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_cadastro)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 851, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ed_pais = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_pais.setObjectName("ed_pais")
        self.gridLayout.addWidget(self.ed_pais, 0, 1, 1, 1)
        self.ed_ano = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_ano.setObjectName("ed_ano")
        self.gridLayout.addWidget(self.ed_ano, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 7, 0, 1, 1)
        self.ed_krause = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_krause.setObjectName("ed_krause")
        self.gridLayout.addWidget(self.ed_krause, 1, 1, 1, 1)
        self.ed_valor = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_valor.setObjectName("ed_valor")
        self.gridLayout.addWidget(self.ed_valor, 2, 1, 1, 1)
        self.ed_material = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_material.setObjectName("ed_material")
        self.gridLayout.addWidget(self.ed_material, 3, 1, 1, 1)
        self.ed_tamanho = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_tamanho.setObjectName("ed_tamanho")
        self.gridLayout.addWidget(self.ed_tamanho, 4, 1, 1, 1)
        self.ed_anverso = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_anverso.setObjectName("ed_anverso")
        self.gridLayout.addWidget(self.ed_anverso, 5, 1, 1, 1)
        self.ed_foto1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_foto1.setObjectName("ed_foto1")
        self.gridLayout.addWidget(self.ed_foto1, 7, 1, 1, 1)
        self.ed_tipo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_tipo.setObjectName("ed_tipo")
        self.gridLayout.addWidget(self.ed_tipo, 1, 3, 1, 1)
        self.ed_moeda = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_moeda.setObjectName("ed_moeda")
        self.gridLayout.addWidget(self.ed_moeda, 2, 3, 1, 1)
        self.ed_venda = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_venda.setObjectName("ed_venda")
        self.gridLayout.addWidget(self.ed_venda, 3, 3, 1, 1)
        self.ed_qualidade = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_qualidade.setObjectName("ed_qualidade")
        self.gridLayout.addWidget(self.ed_qualidade, 4, 3, 1, 1)
        self.ed_reverso = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_reverso.setObjectName("ed_reverso")
        self.gridLayout.addWidget(self.ed_reverso, 5, 3, 1, 1)
        self.ed_foto2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ed_foto2.setObjectName("ed_foto2")
        self.gridLayout.addWidget(self.ed_foto2, 7, 3, 1, 1)
        self.bt_cadastrar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bt_cadastrar.setObjectName("bt_cadastrar")
        self.gridLayout.addWidget(self.bt_cadastrar, 8, 0, 1, 2)
        self.bt_cancelar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.gridLayout.addWidget(self.bt_cancelar, 8, 2, 1, 2)
        self.ed_detalhes = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.ed_detalhes.setObjectName("ed_detalhes")
        self.gridLayout.addWidget(self.ed_detalhes, 6, 1, 1, 3)
        self.lbl_titulo = QtWidgets.QLabel(self.frame_cadastro)
        self.lbl_titulo.setGeometry(QtCore.QRect(10, 10, 851, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.verticalLayout.addWidget(self.frame_cadastro)
        self.frame_listar = QtWidgets.QFrame(self.centralwidget)
        self.frame_listar.setEnabled(True)
        self.frame_listar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_listar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_listar.setObjectName("frame_listar")
        self.listView = QtWidgets.QListView(self.frame_listar)
        self.listView.setGeometry(QtCore.QRect(30, 40, 851, 271))
        self.listView.setObjectName("listView")
        self.lbl_titulo_2 = QtWidgets.QLabel(self.frame_listar)
        self.lbl_titulo_2.setGeometry(QtCore.QRect(30, 10, 851, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo_2.setFont(font)
        self.lbl_titulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo_2.setObjectName("lbl_titulo_2")
        self.verticalLayout.addWidget(self.frame_listar)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName("menubar")
        self.menuCadastrar = QtWidgets.QMenu(self.menubar)
        self.menuCadastrar.setObjectName("menuCadastrar")
        self.menuNacional = QtWidgets.QMenu(self.menuCadastrar)
        self.menuNacional.setObjectName("menuNacional")
        self.menuEstrangeiro = QtWidgets.QMenu(self.menuCadastrar)
        self.menuEstrangeiro.setObjectName("menuEstrangeiro")
        self.menuCadastrar_Novo = QtWidgets.QMenu(self.menubar)
        self.menuCadastrar_Novo.setObjectName("menuCadastrar_Novo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNotas = QtWidgets.QAction(MainWindow)
        self.actionNotas.setObjectName("actionNotas")
        self.actionMoedas = QtWidgets.QAction(MainWindow)
        self.actionMoedas.setObjectName("actionMoedas")
        self.actionNotas_2 = QtWidgets.QAction(MainWindow)
        self.actionNotas_2.setObjectName("actionNotas_2")
        self.actionMoedas_2 = QtWidgets.QAction(MainWindow)
        self.actionMoedas_2.setObjectName("actionMoedas_2")
        self.actionCole_o_Completa = QtWidgets.QAction(MainWindow)
        self.actionCole_o_Completa.setObjectName("actionCole_o_Completa")
        self.actionListar_por_pa_s = QtWidgets.QAction(MainWindow)
        self.actionListar_por_pa_s.setObjectName("actionListar_por_pa_s")
        self.actionPesquisar = QtWidgets.QAction(MainWindow)
        self.actionPesquisar.setObjectName("actionPesquisar")
        self.actionNota = QtWidgets.QAction(MainWindow)
        self.actionNota.setObjectName("actionNota")
        self.actionMoeda = QtWidgets.QAction(MainWindow)
        self.actionMoeda.setObjectName("actionMoeda")
        self.menuNacional.addAction(self.actionNotas)
        self.menuNacional.addAction(self.actionMoedas)
        self.menuEstrangeiro.addAction(self.actionNotas_2)
        self.menuEstrangeiro.addAction(self.actionMoedas_2)
        self.menuCadastrar.addAction(self.actionPesquisar)
        self.menuCadastrar.addSeparator()
        self.menuCadastrar.addAction(self.menuNacional.menuAction())
        self.menuCadastrar.addAction(self.menuEstrangeiro.menuAction())
        self.menuCadastrar.addSeparator()
        self.menuCadastrar.addAction(self.actionCole_o_Completa)
        self.menuCadastrar.addSeparator()
        self.menuCadastrar.addAction(self.actionListar_por_pa_s)
        self.menuCadastrar_Novo.addAction(self.actionNota)
        self.menuCadastrar_Novo.addAction(self.actionMoeda)
        self.menubar.addAction(self.menuCadastrar.menuAction())
        self.menubar.addAction(self.menuCadastrar_Novo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coleção de Moedas e Notas"))
        self.label_3.setText(_translate("MainWindow", "Krause"))
        self.label_2.setText(_translate("MainWindow", "Ano"))
        self.label.setText(_translate("MainWindow", "País"))
        self.label_4.setText(_translate("MainWindow", "Tipo"))
        self.label_5.setText(_translate("MainWindow", "Valor"))
        self.label_7.setText(_translate("MainWindow", "Material"))
        self.label_9.setText(_translate("MainWindow", "Tamanho"))
        self.label_8.setText(_translate("MainWindow", "$ Venda"))
        self.label_6.setText(_translate("MainWindow", "Moeda"))
        self.label_10.setText(_translate("MainWindow", "Qualidade"))
        self.label_11.setText(_translate("MainWindow", "Anverso"))
        self.label_13.setText(_translate("MainWindow", "Detalhes"))
        self.label_15.setText(_translate("MainWindow", "Link foto2"))
        self.label_12.setText(_translate("MainWindow", "Reverso"))
        self.label_14.setText(_translate("MainWindow", "Link foto1"))
        self.bt_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.bt_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.lbl_titulo.setText(_translate("MainWindow", "Cadastrar Item"))
        self.lbl_titulo_2.setText(_translate("MainWindow", "Listar Item"))
        self.menuCadastrar.setTitle(_translate("MainWindow", "Filtrar"))
        self.menuNacional.setTitle(_translate("MainWindow", "Nacional"))
        self.menuEstrangeiro.setTitle(_translate("MainWindow", "Internacional"))
        self.menuCadastrar_Novo.setTitle(_translate("MainWindow", "Cadastrar Novo"))
        self.actionNotas.setText(_translate("MainWindow", "Notas"))
        self.actionMoedas.setText(_translate("MainWindow", "Moedas"))
        self.actionNotas_2.setText(_translate("MainWindow", "Notas"))
        self.actionMoedas_2.setText(_translate("MainWindow", "Moedas"))
        self.actionCole_o_Completa.setText(_translate("MainWindow", "Coleção Completa"))
        self.actionListar_por_pa_s.setText(_translate("MainWindow", "Listar por país"))
        self.actionPesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.actionNota.setText(_translate("MainWindow", "Nota"))
        self.actionMoeda.setText(_translate("MainWindow", "Moeda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

